// Turns the object-type repository (data/object-type-repository.json: how real object alphabets
// were built, letter by letter, sorted into categories) into the small table the app uses to match
// a photo to a category and to build each new letter the way makers in that category did.
//
//   npm run repository          # after editing the JSON
//
// Writes src/core/alphabet/repository-data.ts, one entry per kid-facing category (groups.ts), each
// pooling the finer catalogue categories it takes in. Only counts and object names go into the app.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { GROUPS } from '../src/core/alphabet/groups';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'data', 'object-type-repository.json');
const OUT = join(ROOT, 'src', 'core', 'alphabet', 'repository-data.ts');
const BUILDS = ['single', 'composite', 'repeated', 'formed'] as const;

interface Glyph { char: string; letter: string; case: string; category: string; objects: string; construction: string; confidence: string }
const repo = JSON.parse(readFileSync(SRC, 'utf8')) as { meta: { version: string }; glyphs: Glyph[] };

const out: Record<string, { description: string; count: number; build: number[]; letters: Record<string, { build: number[]; ideas: string[] }> }> = {};
for (const [id, { description, takes }] of Object.entries(GROUPS)) {
  const glyphs = repo.glyphs.filter((g) => takes.includes(g.category) && BUILDS.includes(g.construction as (typeof BUILDS)[number]));
  const build = BUILDS.map((b) => glyphs.filter((g) => g.construction === b).length);
  const letters: Record<string, { build: number[]; ideas: string[] }> = {};
  for (const L of 'ABCDEFGHIJKLMNOPQRSTUVWXYZ') {
    const gs = glyphs.filter((g) => g.letter.toUpperCase() === L);
    if (!gs.length) continue;
    // Object ideas: the confident ones first, most used first, no repeats, no "(unclear)".
    const counts = new Map<string, number>();
    for (const g of gs) {
      if (g.confidence !== 'high' || /unclear/i.test(g.objects)) continue;
      const o = g.objects.trim();
      counts.set(o, (counts.get(o) ?? 0) + 1);
    }
    const ideas = [...counts].sort((a, b) => b[1] - a[1]).map(([o]) => o).slice(0, 4);
    letters[L] = { build: BUILDS.map((b) => gs.filter((g) => g.construction === b).length), ideas };
  }
  out[id] = { description, count: glyphs.length, build, letters };
}

const body =
  `// Generated by scripts/repository.ts from data/object-type-repository.json (v${repo.meta.version}). Do not edit.\n` +
  `// build counts are [single, composite, repeated, formed].\n` +
  `export const REPOSITORY: Record<string, { description: string; count: number; build: number[]; letters: Record<string, { build: number[]; ideas: string[] }> }> = ${JSON.stringify(out)};\n`;
writeFileSync(OUT, body);
console.log(`wrote ${OUT}: ${Object.keys(out).length} categories, ${(body.length / 1024).toFixed(1)} KB`);
